### PR TITLE
Presentation Page

### PR DESCRIPTION
**Pull request by AutinMitra**
https://www.figma.com/file/62ByqrNpfWiNRXeBJQbZmH/TJCSC

Contains functionality : )

### CODE REVIEW

**Review by AutinMitra — COMMENTED** [review]
We may want to extract the dropdown to a separate component

**Comment by DarinMao** [comment]
should the search box be debounced a little bit? I doubt performance will improve with only ten presentations but it seems like a good idea

**Comment by AutinMitra** [comment]
Yeah 50-100ms debouncing could be nice, will implement later tonight (10ish?)

**Review by DarinMao — APPROVED** [review]
I think this is alright for now, you can pull the dropdown out into a component if you want

**Pull request merged**
